name: multi_repo
description: Manage repositories with multiple Dart packages
version: 0.0.1-dev
homepage: https://github.com/dart-lang/multi_repo
author: Dart Team <misc@dartlang.org>

environment:
  sdk: '>=1.24.0 <2.0.0-dev.infinity'

dependencies:
  args: ">=0.13.7 <2.0.0"
  path: ^1.4.1
  pub_semver: ^1.3.2
  yaml: ^2.1.12

dev_dependencies:
  test: ^0.12.0
